default: &default
  username: postgres
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 30000

development:
  <<: *default
  database: api-dtl_development
test:
  adapter: postgresql
  encoding: unicode
  database: dtl_test
  pool: 5
  host: <%= ENV['DBHOST'] %>
  username: dtl-api-rails
  password: <%= ENV['DBPWD'] %>
production:
  adapter: postgresql
  encoding: unicode
  database: dtl_production
  pool: 5
  host: <%= ENV['DBHOST'] %>
  username: dtl-api-rails
  password: <%= ENV['DBPWD'] %>