default: &default
  username: postgres
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 30000

development:
  <<: *default
  database: api-dtl_development
production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: dtl_production
    pool: 5
    host: <%= ENV['DBHOST'] %>
    username: dtl-api-rails
    password: <%= ENV['DBPWD'] %>
  animals:
    adapter: mysql2
    encoding: utf8
    socket: /var/run/mysqld/mysqld.sock
    pool: 5
    host: <%= ENV['PHOST'] %>
    database: <%= ENV['PDB'] %>
    username: <%= ENV['PU'] %>
    password: <%= ENV['PPW'] %>
