development:
  adapter: postgresql
  encoding: unicode
  database: dtl_development
  pool: 5
  host: 34.80.225.95
  username: dtl-api-rails
  password: <%= ENV['DBPWD'] %>
test:
  adapter: postgresql
  encoding: unicode
  database: dtl_test
  pool: 5
  host: 34.80.225.95
  username: dtl-api-rails
  password: <%= ENV['DBPWD'] %>
